apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-server
  labels:
    app: time-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-server
  template:
    metadata:
      labels:
        app: time-server
    spec:
      containers:
      - name: time-server
        image: time-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: time-server-svc
spec:
  selector:
    app: time-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 31000
  type: NodePort 
