name: "beer-reviews"

services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile_server
    ports:
      - "8080:8080"
    image: beer-reviews-api

  rater:
    build:
      context: ../
      dockerfile: docker/Dockerfile_review_rater
    image: beer-reviews-rater

  # PostgreSQL
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123asd123
      POSTGRES_DB: beer_reviews
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d beer_reviews"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Jaeger All-in-One
  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # HTTP collector
      - "6831:6831/udp" # Jaeger agent (UDP)
    environment:
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:16686"]
      interval: 10s

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ../grafana_data:/var/lib/grafana
      - ../grafana_provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ../../ollama_data:/root/.ollama

volumes:
  postgres_data:
  grafana_data:
  ollama_data:
